version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: facesocial-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Boss.1212
      POSTGRES_DB: facesocial
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: facesocial-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@facesocial.com
      PGADMIN_DEFAULT_PASSWORD: Boss.1212
    depends_on:
      - postgres

volumes:
  postgres-data: