version: '3.8'
services:
  facenet-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - .:/app
    restart: unless-stopped
    environment:
      - MODEL_PATH=/app/models/facenet/20180402-114759/20180402-114759.pb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload